### ISSUE TITLE
Class FormatWikiText : function getTableau() doesn't work

### ISSUE THREAD

**Issue by ChibiMG** [ChibiMG/PDL_2018-2019_GR3#15]
There is an error : array index out of bounds exception when the test is started in the class TestWikiText.

**Comment by hheinle** [comment]
getTableau() is now in the class ParserWikitext with the signature "String getTable()". As the older version, it gets one table from the page.
There is no more exception. (commit 5ac918e28b7c982030e511568e2267998565bf09)
