### ISSUE TITLE
TestWikiText : method getHead() and headToCSV()

### ISSUE THREAD

**Issue by sknab** [ChibiMG/PDL_2018-2019_GR3#16]
Test : error
ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

Result expected :
The header of the table

**Comment by sknab** [comment]
Then, headToCSV have the same error (because it use getHead method)

**Comment by hheinle** [comment]
The new class which is in charge of parsing wikitext (ParserWikiText.java), doesn't include a specific method to handle the table's head. It's handled like a normal row. (commit 84b2bcace56f9e2c9bd15d66e3324ee7ee9d1f17)

headToCsv() doesn't exist anymore in ParserWikiText. To separate classes role, a class Converter was created. ParserWikiText is not in charge of converting in csv. (commit b08182d : b08182d#diff-a7620b1ef0f2b3e71fe577bb275cfae2)
