### ISSUE TITLE
Class FormatWikitest : getRow() & rowToCSV()

### ISSUE THREAD

**Issue by ChibiMG** [ChibiMG/PDL_2018-2019_GR3#17]
There is an error in getRow() : array index out of bounds exception when the test is started.

It's the same in rowToCSV() because it is connected with getRow().

**Comment by hheinle** [comment]
getRow() is now in the class ParserWikitext with the signature "ArrayList<String> getRowsFromTable(final String table)". As the older version, it gets the rows from one table.
There is no more exception. (commit 4963beee224a22020751ebc9f1dc57e9986720ee : https://github.com/ChibiMG/PDL_2018-2019_GR3/commit/4963beee224a22020751ebc9f1dc57e9986720ee#diff-2ab90e8953ce5cc811060ec43640cee6)

rowToCsv() doesn't exist anymore in ParserWikiText. To separate classes role, a class Converter was created. ParserWikiText is not in charge of converting in csv. (commit b08182d499fcf5fcab7e373a10ef41391e095677 : https://github.com/ChibiMG/PDL_2018-2019_GR3/commit/b08182d499fcf5fcab7e373a10ef41391e095677#diff-a7620b1ef0f2b3e71fe577bb275cfae2)
