### ISSUE TITLE
Class FormatWikitext : ToCSV() doesn't work

### ISSUE THREAD

**Issue by ChibiMG** [ChibiMG/PDL_2018-2019_GR3#18]
Error : Array index out of bounds exception

It's because this method is connected with rowToCSV() and headToCSV().

**Comment by hheinle** [comment]
[Issue 16]( https://github.com/ChibiMG/PDL_2018-2019_GR3/issues/16)
and
[Issue 17](https://github.com/ChibiMG/PDL_2018-2019_GR3/issues/17)
