### ISSUE TITLE
Test failed in TestParserComparison

### ISSUE THREAD

**Issue by hheinle** [ChibiMG/PDL_2018-2019_GR3#21]
TestParserComparison return 59% for ParserWikiText : 
the result returned is not 100% because, in wikitext, there is a particular syntax allowing to form an array. There are characters to separate cells, lines ... However, the implementation differs depending on the Wikipedia pages and the contributor. ParserWikitext has regular expressions allowing to capture separators, only, they do not capture all cases.

**Comment by yDubois04** [comment]
This issue is moved in issue #22
