### ISSUE TITLE
Problems in getTitle () in FormatHTML in some languages

### ISSUE THREAD

**Issue by yDubois04** [ChibiMG/PDL_2018-2019_GR3#4]
Class : FormatHTML.java

This issue has some consequences in CSV method in fact getTitle () doesn't return a valid title so this method can't create a valid file (title is too long)

**Comment by BolbiKet** [comment]
Possible correction for getTitle() : 
In the english HTML, the title is marked as follow : <title>Page title - Wikipedia</title>
In the code, getTitle() want to get "Page title" so the code split out "- Wikipedia"

But in french, the title is marked like this : <title>Itoku — Wikipédia</title>
The separation char is different from the english one("-" in english, "—" in french), which prevent the actual code from extracting the title from the french HTML...

In other language, the same error can happend (in chinese for exemple, where wikipedia is written in Hanzi).

A solution could be to extract the title from "<title>" to "</title>", which would allow any langage to pass...

**Comment by yDubois04** [comment]
Now when you create a processWikiUrl, you must specified the langage
